### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by paul59** [PhilMoe/cerberus#151]
Hi Phil

Are there any build instructions fro Linux around? I see the website/forum is no longer active and the instructions here on github are a bit too vague for my level of knowledge!

Cheers

Paul

**Comment by PhilMoe** [comment]
@paul59 
Hey Paul,

Mike thankfully set up a temporary readonly version of the old forum [here at www.fantomgl.com](https://www.fantomgl.com/index.php)
while I am working on the new one. I will set up a link to it from our cx domain as soon as I have the legal things ready. 

Bye, 

Phil

**Comment by paul59** [comment]
Great, many thanks!

**Comment by PhilMoe** [comment]
@MikeHart66 No, just the Impressum and privacy policy in German and Englisch.
